name: cicd-deploy-versioning

# on:
#   push:
#     branches:
#       - main
#       - dev
#       - staging
#       - feature
#       - uat

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-java
      - uses: ./.github/actions/maven-compile

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-java
      - uses: ./.github/actions/maven-test

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-java
      - uses: ./.github/actions/maven-package-upload

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: app-jar
          path: app

      - name: Set Environment Variables Based on Branch
        uses: ./.github/actions/set-env-by-branch
        with:
          branch: ${{ github.ref_name }}

      - name: Build and Push Docker Image to ECR
        uses: ./.github/actions/docker-build-push
        with:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: us-east-1
           ecr-repo-name: ${{ secrets.AWS_ECR_REPOSITORY_NAME }}
